// ─── Master Projects Data ─────────────────────────────────────────────────────
// Level 1 → categories
// Level 2 → subcategories (category page)
// Level 3 → individual projects (carousel)
// Level 4 → full case study (auto-built from project data)

export const projectsData = {
    "3d": {
        id: "3d",
        label: "3D Art",
        tag: "Blender · Animation",
        description: "3D characters, cinematic animations and product visualizations created using Blender.",
        previewImages: [
            "/projects/character/miles/miles_thumb.png",
            "/projects/character/astranaut/astranaut_thumb.png",
            "/projects/animation/client_home/client_home_thumb.png",
        ],
        subcategories: [
            {
                id: "character",
                name: "Character Design",
                description: "Stylized character creation — from concept sketch to fully rendered 3D model.",
                icon: "👤",
                projects: [
                    {
                        id: "char-01",
                        title: "Astronaut Character",
                        subtitle: "Stylized 3D · Blender",
                        description: "A stylized astronaut character model.",
                        src: "/projects/character/astranaut/astranaut_thumb.png",
                        modelUrl: "/projects/character/astranaut/astranaut.glb",
                        tools: ["Blender"],
                        overview: "A sci-fi astronaut character modeled and rigged for animation. Built from the ground up for use in stylized cinematic sequences, the model features organic topology, expressive facial rigging, and meticulously hand-painted textures. The core focus here was to create a portfolio-grade character demonstrating not only structural integrity for animation but also cohesive aesthetic styling and advanced texturing techniques.",
                    },
                    {
                        id: "char-02",
                        title: "Asvind Character",
                        subtitle: "Stylized 3D · Blender",
                        description: "A custom 3D character modeled after Asvind.",
                        src: "/projects/character/asvind/asvind_thumb.png",
                        modelUrl: "/projects/character/asvind/asvind.glb",
                        tools: ["Blender"],
                        overview: "A personalized 3D avatar featuring intricate facial expressions, customized clothing, and dynamic rigging designed for a variety of scenes. Developing this stylized self-portrait required capturing a distinct likeness while maintaining a cohesive, semi-realistic yet stylized aesthetic. Extensive texturing allowed for high-fidelity clothing textures, while the comprehensive rigging setup ensures versatility for various animation projects.",
                    },
                    {
                        id: "char-03",
                        title: "Miles Morales",
                        subtitle: "Stylized 3D · Blender",
                        description: "A 3D character model inspired by Miles Morales Spider-Man.",
                        src: "/projects/character/miles/miles_thumb.png",
                        modelUrl: "/projects/character/miles/miles_character.glb",
                        textureUrl: "/projects/character/miles/texture.png",
                        tools: ["Blender"],
                        overview: "A highly dynamic Spider-Man character built with comic-book style texturing and advanced athletic rigging for extreme action poses. Inspired by the animated films, this model integrates custom halftone shaders and stylized edge lighting directly within Blender. To achieve the iconic acrobatic fluidity, the rigging demanded complex constraints and specialized weight painting, allowing the character to stretch and bend dynamically without losing form.",
                    },
                ],
            },
            {
                id: "animation",
                name: "3D Animation",
                description: "Cinematic animation scenes with dynamic movement, particles, and storytelling.",
                icon: "🎬",
                projects: [
                    {
                        id: "anim-01",
                        title: "Home Video Animation",
                        subtitle: "3D Animation · Blender",
                        description: "A cinematic home / architecture video animation for a client.",
                        src: "/projects/animation/client_home/client_home_thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/q_auto/f_auto/v1781024057/client_home_akukdm.mp4",
                        tools: ["Blender"],
                        overview: "A 3D architectural animation showing a complete house layout with realistic lighting, moving camera angles, and high-quality materials. The goal was to deliver a premium architectural visualization video that highlights both the inviting exterior environment and the spacious interior of a modern home. Utilizing global illumination and photorealistic textures, the sequence guides the viewer through the primary living spaces with calculated, cinematic camera moves.",
                    },
                    {
                        id: "anim-02",
                        title: "My Intro Animation",
                        subtitle: "3D Animation · Blender",
                        description: "A bold, dynamic intro sequence utilizing 3D motion graphics.",
                        src: "/projects/animation/intro/intro_animation_thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/q_auto/f_auto/v1781024934/intro_animation_ark6ip.mp4",
                        tools: ["Blender"],
                        overview: "A personal branding intro animation utilizing high-impact 3D camera sweeps, dynamic lighting, and stylized visual effects to kick off videos. Created to serve as a memorable personal brand identity intro, it balances professional 3D rendering quality with a punchy, energetic tone. The sequence combines rapid edits, metallic surface reflections, and deep, immersive sound design to instantly capture audience attention.",
                    },
                    {
                        id: "anim-03",
                        title: "Car Showcase",
                        subtitle: "3D Animation · Blender",
                        description: "A high-octane cinematic car animation with neon lighting and dynamic camera work.",
                        src: "/projects/animation/car/car_thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/q_auto/f_auto/v1781023790/car_hbnzjs.mp4",
                        tools: ["Blender"],
                        overview: "A sleek automotive animation showcasing a futuristic sports car with neon underglow, dramatic studio lighting, and cinematic camera movements. The project pushed photorealistic car rendering techniques — from custom paint shaders and reflective surface materials to timed camera sweeps that highlight every curve and edge. Designed to match the production quality of modern automotive commercials.",
                    },
                ],
            },
            {
                id: "product",
                name: "Product Animation",
                description: "Product visualization and animation for commercial and portfolio use.",
                icon: "📦",
                projects: [
                    {
                        id: "prod-01",
                        title: "Airpods Showcase",
                        subtitle: "Product Viz · Blender",
                        description: "3D animated product reveal for wireless Airpods.",
                        src: "/projects/product/airpods/airpods_thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/q_auto/f_auto/v1781023859/airpods_vrwgb3.mp4",
                        tools: ["Blender"],
                        overview: "A smooth product reveal animation showcasing the iconic design of the Airpods. Highlights sleek curves, accurate material finishes, and a studio lighting environment crafted to mimic Apple's premium marketing style. The project involved modeling with extremely high subdivision levels to maintain perfectly rounded edges under extreme macro camera angles.",
                    },
                    {
                        id: "prod-02",
                        title: "Coca-Cola Refresh",
                        subtitle: "Product Viz · Blender",
                        description: "Dynamic product animation for a Coke can.",
                        src: "/projects/product/coke/coke_thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/q_auto/f_auto/v1781023857/coke_du5qk9.mp4",
                        tools: ["Blender"],
                        overview: "A visually striking product visualization of a Coca-Cola can featuring high-energy camera movements, condensation droplets, and dramatic lighting to evoke refreshment. Designed to push photorealistic rendering and fluid simulation techniques to commercial advertising standards, the animation leverages intricate particle systems for the condensation and subsurface scattering for the liquid.",
                    },
                    {
                        id: "prod-03",
                        title: "iPhone Commercial",
                        subtitle: "Product Animation · Blender",
                        description: "A stylized, high-tech commercial rendering of an iPhone.",
                        src: "/projects/product/iphone/iphone_thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/q_auto/f_auto/v1781024021/iphone_qquiun.mp4",
                        tools: ["Blender"],
                        isVertical: true,
                        overview: "A fast-paced, horizontal format product display animation focusing on the screen, lens array, and glowing accents of the modern iPhone. Created to build a high-fidelity technology commercial combining precision modeling with dynamic post-effects, the project heavily integrated After Effects for glowing UI overlays, optical flares, and sharp, rhythm-based scene transitions.",
                    },
                ],
            },
        ],
    },

    motion: {
        id: "motion",
        label: "Motion Graphics & Editing",
        tag: "After Effects · Premiere Pro",
        description: "Motion design and video editing projects created using After Effects and Premiere Pro.",
        previewImages: [
            "/projects/motion/mograph/thumb.png",
            "/projects/motion/social2/thumb.png",
            "/projects/motion/techlife/thumb.png",
        ],
        subcategories: [
            {
                id: "reels",
                name: "Mograph",
                description: "Dynamic motion design reels and 3D mograph showcases.",
                icon: "🎞️",
                projects: [
                    {
                        id: "mograph-01",
                        title: "Mograph Showcase",
                        subtitle: "3D Motion · After Effects",
                        description: "Sleek and responsive UI motion design focused on intuitive user experiences.",
                        src: "/projects/motion/mograph/thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/v1783399925/mograph_1_ufxrn2.mp4",
                        tools: ["After Effects", "Blender"],
                        isVertical: true,
                        overview: "A refined and dynamic UI motion sequence demonstrating modern interface animation principles. This project focuses on clean aesthetics, responsive micro-interactions, and fluid transitions that elevate the digital experience. By emphasizing timing, easing, and spatial awareness, it brings digital elements to life, bridging the gap between functional design and interactive storytelling.",
                    },
                ],
            },
            {
                id: "social",
                name: "Social Media",
                description: "Animated content for social media platforms — Instagram, TikTok and more.",
                icon: "📱",
                projects: [
                    {
                        id: "social-2",
                        title: "Social Media Reel",
                        subtitle: "Promo · Premiere Pro",
                        description: "Dynamic vertical edit for high-engagement social platforms.",
                        src: "/projects/motion/social2/thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/q_auto/f_auto/v1781023311/video_xz9euv.mp4",
                        tools: ["Premiere Pro", "After Effects"],
                        isVertical: true,
                        overview: "A fast-paced social media reel designed for maximum engagement, featuring snappy transitions, bold typography, and synchronized sound design.",
                    },
                    {
                        id: "tech-life",
                        title: "Tech-Life Story",
                        subtitle: "Lifestyle · After Effects",
                        description: "A professional tech-lifestyle montage with polished motion graphics.",
                        src: "/projects/motion/techlife/thumb.png",
                        videoUrl: "https://res.cloudinary.com/dkrskphqb/video/upload/q_auto/f_auto/v1781023671/video_jp6aoz.mp4",
                        tools: ["After Effects", "Premiere Pro"],
                        isVertical: true,
                        overview: "A cinematic look into the tech-driven lifestyle, combining high-quality footage with minimalist motion overlays and smooth transitions.",
                    },
                ],
            },
        ],
    },
};
